apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-saas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-saas-app
  template:
    metadata:
      labels:
        app: restaurant-saas-app
    spec:
      containers:
      - name: backend
        image: backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 3001
